AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application
Parameters:
  Environment:
    Variables:
      TABLE_NAME: ShortenedUris
Resources:
  Lookup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: shortener.lookup
      Runtime: nodejs6.10
      CodeUri: s3://joneschr-brnr-1214-a-lambdas/shortener.zip
